### ISSUE TITLE
Create Users Table

### ISSUE THREAD

**Issue by Mythotical** [Mythotical/SWDV691-Listopia#1]
**Description:** Stores user information for authentication and personalization.
**Usage:** Handles user authentication, registration, and profile management.
**Columns:**
- `user_id` (Primary Key): Unique identifier for each user.
- `username`: User's chosen username.
- `password`: Hashed password for authentication.
- `email`: User's email address.

**Tasks**
- [x] Create PostgreSQL table
- [x] Implement user registration endpoint
- [x] Implement user login endpoint
- [x] Handle authentication errors

#6 #5
